
Metrics = {
	'1-day active users': 'active1DayUsers',
	'28-day active users': 'active28DayUsers',
	'7-day active users': 'active7DayUsers',
	'Active users': 'activeUsers',
	'Ad unit exposure': 'adUnitExposure',
	'Add-to-carts': 'addToCarts',
	'Average purchase revenue': 'averagePurchaseRevenue',
	'ARPPU': 'averagePurchaseRevenuePerPayingUser',
	'Average purchase revenue per user': 'averagePurchaseRevenuePerUser',
	'ARPU': 'averageRevenuePerUser',
	'Average session duration': 'averageSessionDuration',
	'Bounce rate': 'bounceRate',
	'Cart-to-view rate': 'cartToViewRate',
	'Checkouts': 'checkouts',
	'Cohort active users': 'cohortActiveUsers',
	'Cohort total users': 'cohortTotalUsers',
	'Conversions': 'conversions',
	'Crash-affected users': 'crashAffectedUsers',
	'Crash-free users rate': 'crashFreeUsersRate',
	'DAU / MAU': 'dauPerMau',
	'DAU / WAU': 'dauPerWau',
	'Ecommerce purchases': 'ecommercePurchases',
	'Engaged sessions': 'engagedSessions',
	'Engagement rate': 'engagementRate',
	'Event count': 'eventCount',
	'Event count per user': 'eventCountPerUser',
	'Event value': 'eventValue',
	'Events per session': 'eventsPerSession',
	'First-time purchaser conversion': 'firstTimePurchaserConversionRate',
	'First time purchasers': 'firstTimePurchasers',
	'First-time purchasers per new user': 'firstTimePurchasersPerNewUser',
	'Item list click through rate': 'itemListClickThroughRate',
	'Item list clicks': 'itemListClicks',
	'Item list views': 'itemListViews',
	'Item promotion click through rate': 'itemPromotionClickThroughRate',
	'Item promotion clicks': 'itemPromotionClicks',
	'Item promotion views': 'itemPromotionViews',
	'Item purchase quantity': 'itemPurchaseQuantity',
	'Item revenue': 'itemRevenue',
	'Item views': 'itemViews',
	'New users': 'newUsers',
	'Organic google search average position': 'organicGoogleSearchAveragePosition',
	'Organic google search click through rate': 'organicGoogleSearchClickThroughRate',
	'Organic google search clicks': 'organicGoogleSearchClicks',
	'Organic google search impressions': 'organicGoogleSearchImpressions',
	'Publisher ad clicks': 'publisherAdClicks',
	'Publisher ad impressions': 'publisherAdImpressions',
	'Purchase revenue': 'purchaseRevenue',
	'Purchase-to-view rate': 'purchaseToViewRate',
	'Purchaser conversion': 'purchaserConversionRate',
	'Views': 'screenPageViews',
	'Views per session': 'screenPageViewsPerSession',
	'Sessions': 'sessions',
	'Sessions per user': 'sessionsPerUser',
	'Shipping amount': 'shippingAmount',
	'Tax amount': 'taxAmount',
	'Total ad revenue': 'totalAdRevenue',
	'Total purchasers': 'totalPurchasers',
	'Total revenue': 'totalRevenue',
	'Total users': 'totalUsers',
	'Transactions': 'transactions',
	'Transactions per purchaser': 'transactionsPerPurchaser',
	'User engagement': 'userEngagementDuration',
	'WAU / MAU': 'wauPerMau'
}