
Dimensions = {
	'Achievement ID': 'achievementId',
	'Ad format': 'adFormat',
	'Ad source': 'adSourceName',
	'Ad unit': 'adUnitName',
	'Age': 'userAgeBracket',
	'App version': 'appVersion',
	'Audience ID': 'audienceId',
	'Audience name': 'audienceName',
	'Browser': 'browser',
	'Campaign': 'campaignName',
	'Campaign ID': 'campaignId',
	'Character': 'character',
	'City': 'city',
	'City ID': 'cityId',
	'Cohort': 'cohort',
	'Content ID': 'contentId',
	'Content group': 'contentGroup',
	'Content type': 'contentType',
	'Country': 'country',
	'Country ID': 'countryId',
	'Daily cohort': 'cohortNthDay',
	'Date': 'date',
	'Date + hour (YYYYMMDDHH)': 'dateHour',
	'Date hour and minute': 'dateHourMinute',
	'Day': 'day',
	'Day of week': 'dayOfWeek',
	'Default channel grouping': 'defaultChannelGrouping',
	'Device': 'mobileDeviceMarketingName',
	'Device brand': 'mobileDeviceBranding',
	'Device category': 'deviceCategory',
	'Device model': 'deviceModel',
	'Event name': 'eventName',
	'File extension': 'fileExtension',
	'File name': 'fileName',
	'First session date': 'firstSessionDate',
	'First user Google Ads account name': 'firstUserGoogleAdsAccountName',
	'First user Google Ads ad group ID': 'firstUserGoogleAdsAdGroupId',
	'First user Google Ads ad group name': 'firstUserGoogleAdsAdGroupName',
	'First user Google Ads ad network type': 'firstUserGoogleAdsAdNetworkType',
	'First user Google Ads campaign type': 'firstUserGoogleAdsCampaignType',
	'First user Google Ads creative ID': 'firstUserGoogleAdsCreativeId',
	'First user Google Ads customer ID': 'firstUserGoogleAdsCustomerId',
	'First user Google Ads keyword text': 'firstUserGoogleAdsKeyword',
	'First user Google Ads query': 'firstUserGoogleAdsQuery',
	'First user campaign': 'firstUserCampaignName',
	'First user campaign ID': 'firstUserCampaignId',
	'First user default channel grouping': 'firstUserDefaultChannelGrouping',
	'First user manual ad content': 'firstUserManualAdContent',
	'First user manual term': 'firstUserManualTerm',
	'First user medium': 'firstUserMedium',
	'First user source': 'firstUserSource',
	'First user source / medium': 'firstUserSourceMedium',
	'First user source platform': 'firstUserSourcePlatform',
	'Full page URL': 'fullPageUrl',
	'Gender': 'userGender',
	'Google Ads account name': 'googleAdsAccountName',
	'Google Ads ad group ID': 'googleAdsAdGroupId',
	'Google Ads ad group name': 'googleAdsAdGroupName',
	'Google Ads ad network type': 'googleAdsAdNetworkType',
	'Google Ads campaign type': 'googleAdsCampaignType',
	'Google Ads creative ID': 'googleAdsCreativeId',
	'Google Ads customer ID': 'googleAdsCustomerId',
	'Google Ads keyword text': 'googleAdsKeyword',
	'Google Ads query': 'googleAdsQuery',
	'Group ID': 'groupId',
	'Hostname': 'hostName',
	'Hour': 'hour',
	'Interests': 'brandingInterest',
	'Is conversion event': 'isConversionEvent',
	'Item ID': 'itemId',
	'Item affiliation': 'itemAffiliation',
	'Item brand': 'itemBrand',
	'Item category': 'itemCategory',
	'Item category 2': 'itemCategory2',
	'Item category 3': 'itemCategory3',
	'Item category 4': 'itemCategory4',
	'Item category 5': 'itemCategory5',
	'Item list ID': 'itemListId',
	'Item list name': 'itemListName',
	'Item name': 'itemName',
	'Item promotion ID': 'itemPromotionId',
	'Item promotion creative name': 'itemPromotionCreativeName',
	'Item promotion name': 'itemPromotionName',
	'Item variant': 'itemVariant',
	'Landing page': 'landingPage',
	'Language': 'language',
	'Language code': 'languageCode',
	'Level': 'level',
	'Link ID': 'linkId',
	'Link URL': 'linkUrl',
	'Link classes': 'linkClasses',
	'Link domain': 'linkDomain',
	'Link text': 'linkText',
	'Manual ad content': 'manualAdContent',
	'Manual term': 'manualTerm',
	'Medium': 'medium',
	'Method': 'method',
	'Minute': 'minute',
	'Mobile model': 'mobileDeviceModel',
	'Month': 'month',
	'Monthly cohort': 'cohortNthMonth',
	'New / returning': 'newVsReturning',
	'Nth day': 'nthDay',
	'Nth hour': 'nthHour',
	'Nth minute': 'nthMinute',
	'Nth month': 'nthMonth',
	'Nth week': 'nthWeek',
	'Nth year': 'nthYear',
	'OS version': 'operatingSystemVersion',
	'Operating system': 'operatingSystem',
	'Operating system with version': 'operatingSystemWithVersion',
	'Order coupon': 'orderCoupon',
	'Outbound': 'outbound',
	'Page location': 'pageLocation',
	'Page path': 'pagePath',
	'Page path + query string': 'pagePathPlusQueryString',
	'Page path + query string and screen class': 'unifiedPageScreen',
	'Page path and screen class': 'unifiedPagePathScreen',
	'Page referrer': 'pageReferrer',
	'Page title': 'pageTitle',
	'Page title and screen class': 'unifiedScreenClass',
	'Page title and screen name': 'unifiedScreenName',
	'Percent scrolled': 'percentScrolled',
	'Platform': 'platform',
	'Platform / device category': 'platformDeviceCategory',
	'Region': 'region',
	'Screen resolution': 'screenResolution',
	'Search term': 'searchTerm',
	'Session Google Ads account name': 'sessionGoogleAdsAccountName',
	'Session Google Ads ad group ID': 'sessionGoogleAdsAdGroupId',
	'Session Google Ads ad group name': 'sessionGoogleAdsAdGroupName',
	'Session Google Ads ad network type': 'sessionGoogleAdsAdNetworkType',
	'Session Google Ads campaign type': 'sessionGoogleAdsCampaignType',
	'Session Google Ads creative ID': 'sessionGoogleAdsCreativeId',
	'Session Google Ads customer ID': 'sessionGoogleAdsCustomerId',
	'Session Google Ads keyword text': 'sessionGoogleAdsKeyword',
	'Session Google Ads query': 'sessionGoogleAdsQuery',
	'Session campaign': 'sessionCampaignName',
	'Session campaign ID': 'sessionCampaignId',
	'Session default channel grouping': 'sessionDefaultChannelGrouping',
	'Session manual ad content': 'sessionManualAdContent',
	'Session manual term': 'sessionManualTerm',
	'Session medium': 'sessionMedium',
	'Session source': 'sessionSource',
	'Session source / medium': 'sessionSourceMedium',
	'Session source platform': 'sessionSourcePlatform',
	'Shipping tier': 'shippingTier',
	'Signed in with user ID': 'signedInWithUserId',
	'Source': 'source',
	'Source / medium': 'sourceMedium',
	'Source platform': 'sourcePlatform',
	'Stream ID': 'streamId',
	'Stream name': 'streamName',
	'Test data filter name': 'testDataFilterName',
	'Transaction ID': 'transactionId',
	'Video URL': 'videoUrl',
	'Video provider': 'videoProvider',
	'Video title': 'videoTitle',
	'Virtual currency name': 'virtualCurrencyName',
	'Visible': 'visible',
	'Week': 'week',
	'Weekly cohort': 'cohortNthWeek',
	'Year': 'year'
}

